In [1]:
%matplotlib inline
import numpy as np
from Libs import stats as st, metrics as m, resample as r, linear_model as lm
from sklearn import linear_model, metrics
from math import sqrt

# 2. a) a) Represente os dados a seguir:

https://www.kdnuggets.com/wp-content/uploads/historical-housing-data.png

In [2]:
data = np.array([[1400, 245.000], [1600, 312.000], [1700, 279.000], [1875, 308.000], [1100, 199.000], 
                   [1550, 219.000], [2350, 405.000], [2450, 324.000], [1425, 319.000], [1700, 255.000]])

# 2. b) Calcule média, desvio padrão e variância de X.

In [3]:
X = data[:, 0]
y = data[:, 1]

X, y

(array([ 1400.,  1600.,  1700.,  1875.,  1100.,  1550.,  2350.,  2450.,
         1425.,  1700.]),
 array([ 245.,  312.,  279.,  308.,  199.,  219.,  405.,  324.,  319.,  255.]))

In [4]:
print("Média = {}".format(st.mean(X)))
print("Desvio padrão = {}".format(st.stdev(X)))
print("Variância = {}".format(st.var(X)))

Média = 1715.0
Desvio padrão = 396.42149285829595
Variância = 157150.0


In [5]:
# Teste
np.mean(X), np.std(X), np.var(X)

(1715.0, 396.42149285829595, 157150.0)

# 2. c) Divida os dados X, y para 70% de treino e 30% de teste. O resultado deve estar nas variáveis: X_train, y_train, X_test, y_test.
## Dicas: 
### X_train = X[idx_train], onde idx_train é um array com os índices dos dados de treino.
### y_train = y[idx_train]
### X_test = X[idx_test]
### y_test = y[idx_test]

In [6]:
idx_train, idx_test = r.split_train_test(len(X), 0.7, 0)

idx_train, idx_test

([2, 8, 4, 9, 1, 6, 7], [3, 0, 5])

In [7]:
X_train = X[idx_train]
y_train = y[idx_train]
X_test = X[idx_test]
y_test = y[idx_test]

y_train, X_test, y_test

(array([ 279.,  319.,  199.,  255.,  312.,  405.,  324.]),
 array([ 1875.,  1400.,  1550.]),
 array([ 308.,  245.,  219.]))

# 2. d) Crie um modelo de (1) SimpleLinearRegression (sua implementação) e outro modelo usando (2) LinearRegression do Scikit Learn.

In [8]:
model1 = lm.SimpleLinearRegression()
model2 = linear_model.LinearRegression()

# 2. e) Treine os modelos com os dados de treino (X_train, y_train).

In [9]:
model1.fit(X_train, y_train)
b0_1 = model1.b0
b1_1 = model1.b1

b0_1, b1_1

(122.46752256260331, 0.10026185331130034)

In [10]:
X_train2 = [[i] for i in X_train]
model2.fit(X_train2, y_train)
b1_2 = model2.coef_
b0_2 = model2.intercept_

b0_2, b1_2[0]

(122.46752256260328, 0.10026185331130037)

# 2. f) Faça as predições para os modelos usando os dados de teste (X_test).

In [11]:
y_pred = model1.predict(X_test)

X_test, y_pred

(array([ 1875.,  1400.,  1550.]),
 array([ 310.45849752,  262.8341172 ,  277.8733952 ]))

In [12]:
X_test2 = [[i] for i in X_test]
y_pred2 = model2.predict(X_test2)

X_test2, y_pred2

([[1875.0], [1400.0], [1550.0]],
 array([ 310.45849752,  262.8341172 ,  277.8733952 ]))

# 2. g) Calcule as métricas MSE, RMSE e MAE para avaliar os modelos criados comparando os rótulos dos dados de teste (y_test) com os dados preditos (y_pred).

In [13]:
mse = m.mse(y_test, y_pred)
rmse = m.rmse(y_test, y_pred)
mae = m.mae(y_test, y_pred)

mse, rmse, mae

(1263.3922027033184, 35.544228824146941, 26.388669971611364)

In [14]:
mse_2 = metrics.mean_squared_error(y_test, y_pred2)
rmse_2 = sqrt(metrics.mean_squared_error(y_test, y_pred2))
mae_2 = metrics.mean_absolute_error(y_test, y_pred2)

mse_2, rmse_2, mae_2

(1263.3922027033184, 35.54422882414694, 26.388669971611364)